version: "3"
services:
  songservice:
    image: songservice
    ports:
      - "8084:8084"
    networks:
      - songservice-mysqldb_1
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - songservice-mysqldb_1
    environment:
      - MYSQL_ROOT_PASSWORD=tOf4s34_2
      - MYSQL_DATABASE=song_service
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

networks:
  songservice-mysql:
  songservice-mysqldb_1: